# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea19046f79f5a176dd0eb76b86996caae6338ec55301ebc4ecab872ca5c4512a6cabb4da4d2471c2d14cc4aa9fa06f89e030cfb1b9dc546c1de47f99e2dd505c

test:
  secret_key_base: fb112d46c5d886295b6bb60991d8bc3fe3be40470ab3a247650ea0713bd440bbc2a15eab4160f50d7d1fb2d3f7b82b059d6186a67bcf63a2444039b4c0aedd39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
